### ISSUE TITLE
新的赵云杯开始了，求更新

### ISSUE THREAD

**Issue by starxjys** [RainbowTalaxy/blog#73]
感谢大佬

**Comment by RainbowTalaxy** [comment]
我回去看下录播吧，了解下什么新规则

**Comment by RainbowTalaxy** [comment]
在进开发了，但是可能比较慢。不过感觉这个帖子也够了😂

**Comment by RainbowTalaxy** [comment]
@starxjys 这周有空了，预计这两天结掉开发，但是需要一个数据录入员。同时还需要有人归纳一下记分方式，我才好做出数据面板出来，这个官方的比赛规则和记分方式描述得实在是太难看了哈哈哈哈

**Comment by starxjys** [comment]
可以参考一下
https://weibo.com/7299640418
https://space.bilibili.com/1403959/dynamic
